---
files: ^(.*\.(py|json|md|sh|yaml|yml|cfg|txt))$
exclude: ^(\.[^/]*cache/.*|demo/.*|debug/.*|.github/ISSUE_TEMPLATE)$
repos:
  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat # Executable to run, with fixed options
        language: python
        types: [markdown]
        exclude: ^(\.github/ISSUE_TEMPLATE.*)$
        args: [--wrap, "75", --number]
        additional_dependencies:
          - mdformat-toc
          - mdformat-beautysh
          - mdformat-config
          - mdformat-gfm
          - setuptools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        # Exclude because of bug in checker
        exclude: ^(docker-compose\.yml|.*/release-drafter\.yml)$
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: pretty-format-json
        exclude: ^(\.vscode|\.devcontainer)
        args:
          # order of keys in manifest.json is "special"
          - --no-sort-keys
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^(.*\.md)$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - "{extends: relaxed, rules: {line-length: {max: 90}}}"
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - -l 79
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, "B105,B110,B311,B404,B603", --recursive, apps]
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.4.1
    hooks:
      - id: autoflake8
        args:
          - -i
          - -r
          - --expand-star-imports
          - .
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pyproject-flake8>=0.0.1a2
          - flake8-bugbear>=22.1.11
          - flake8-comprehensions>=3.8.0
          - flake8_2020>=1.6.1
          - mccabe
          - pycodestyle>=2.10.0
          - pyflakes>=2.4.0
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-Ldout]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        # exclude: ^$
        args:
          - --reports=no
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --check-untyped-defs
          - --show-error-codes
          - --show-error-context
        #additional_dependencies:
        #  - types-requests
        #  - urllib3
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
        exclude: (run.sh)$
        additional_dependencies:
          - setuptools
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^[^\.].*\.sh$
        args: [--shell, bash]
